# Generated by Django 5.2.4 on 2025-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
