# Generated by Django 5.2 on 2025-07-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_pages", "0004_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="blog/default.jpg", upload_to="blog/"),
        ),
    ]
