# Generated by Django 5.2 on 2025-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_pages", "0005_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="blog_pages.category"),
        ),
    ]
