# Generated by Django 5.2.4 on 2025-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_pages", "0006_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="counted_view",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
