# Generated by Django 5.2.4 on 2025-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(default="No subject", max_length=255),
        ),
    ]
