# Generated by Django 5.2.4 on 2025-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_contact_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
